import pandas as pd

sample_reviews = [
    "Absolutely wonderful - silky and sexy and comfortable",
    "The material feels soft and luxurious. Very comfortable to wear.",
    "The quality of this dress is excellent and it feels well made.",
    "The fabric feels cheap and started losing shape after one wash.",
    "I love the style of this blouse. It looks modern and elegant.",
    "The fit was perfect and true to size.",
    "This shirt runs very small, so I recommend ordering one size up.",
    "The jeans fit nicely around the waist and hips.",
    "Very comfortable shoes that I can wear all day.",
    "The sweater is cozy, soft, and extremely comfortable.",
    "Beautiful design and stylish enough for both work and dinner.",
    "The stitching is poor and the quality does not justify the price.",
    "The dress is beautiful but the fit is too tight around the chest.",
    "I received many compliments because the style is unique and fashionable.",
    "The pants are comfortable but slightly too long for me.",
    "Excellent quality fabric and the color looks exactly like the pictures.",
    "The material is thin and feels less durable than expected.",
    "This jacket fits perfectly and has a flattering shape.",
    "The style is classic and easy to match with different outfits.",
    "Very soft fabric and comfortable enough for everyday wear.",
    "The sizing was inaccurate and the dress was much larger than expected.",
    "I am impressed with the quality and careful stitching.",
    "This top looks stylish but feels uncomfortable around the shoulders.",
    "The skirt fits well and moves comfortably.",
    "Poor quality zipper and loose threads after only a few uses.",
    "The design is beautiful and the colors are vibrant.",
    "This cardigan is comfortable, warm, and soft.",
    "The fit is awkward and does not match the size chart.",
    "Great quality for the price and the fabric feels durable.",
    "The style is trendy and perfect for casual weekends.",
    "I love how comfortable these leggings are during workouts.",
    "The blouse fits exactly as expected and looks flattering.",
    "The material feels premium and the construction is excellent.",
    "The style was not what I expected from the photos.",
    "These pants are too loose around the waist.",
    "The dress is comfortable and lightweight for summer.",
    "Amazing quality and beautiful attention to detail.",
    "The jacket is stylish but the sleeves are too short.",
    "Soft, comfortable, and easy to wear all day.",
    "The fabric shrank after washing, which was disappointing.",
    "This is one of the most stylish dresses I have purchased.",
    "The fit around the waist is perfect but the length is too long.",
    "The quality exceeded my expectations and feels very durable.",
    "The shirt is uncomfortable because the fabric is rough.",
    "Beautiful style, elegant design, and a very flattering look.",
    "The size was too small even though I ordered my usual size.",
    "The material is soft and the overall quality is impressive.",
    "Very comfortable dress that is perfect for traveling.",
    "The design is fashionable but the fabric quality is average.",
    "These jeans have a perfect fit and are very flattering.",
    "The sweater feels cheap and started pilling quickly.",
    "I love the style and the unique pattern.",
    "The shoes are extremely comfortable and provide good support.",
    "The dress fits beautifully and feels comfortable.",
    "The quality is poor and the seams started coming apart.",
    "The top is stylish, versatile, and easy to dress up.",
    "The pants fit perfectly and the material feels durable.",
    "Comfortable, soft, and perfect for relaxing at home.",
    "The size is too large and the sleeves are much longer than expected.",
    "Excellent fabric quality and beautiful craftsmanship."
]

reviews = pd.DataFrame({"Review Text": sample_reviews})
reviews.to_csv("data/womens_clothing_e-commerce_reviews.csv", index=False)
print("Dataset successfully generated in data/ folder!")
